server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orders}
    username: ${DB_USER:order_user}
    password: ${DB_PASSWORD:order_pass}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoint:
    web:
      exposure:
        include: health,info,metrics,threaddump,httpexchanges